# Generated by Django 5.0.1 on 2024-01-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
