# Generated by Django 5.0 on 2023-12-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_number', models.IntegerField(unique=True)),
                ('national_code', models.IntegerField(unique=True)),
                ('field', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.student')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.representative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.student')),
            ],
        ),
    ]
