# Generated by Django 5.0.1 on 2024-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecart',
            name='votable_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
