# Generated by Django 5.0 on 2023-12-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='field',
        ),
    ]
