# Generated by Django 5.0 on 2023-12-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_vote_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('student', 'representative')},
        ),
    ]
