# Generated by Django 5.0 on 2023-12-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_remove_student_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='field',
        ),
    ]
