# Generated by Django 5.0 on 2023-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_representative_student_alter_vote_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
