# Generated by Django 5.0 on 2023-12-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_representative_number_of_votes_vote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='number_of_votes',
        ),
    ]
