# Generated by Django 5.0.1 on 2024-01-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_code',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
