# Generated by Django 5.0.1 on 2024-03-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_vote_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vote_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
