# Generated by Django 5.0.1 on 2024-03-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_vote_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='field',
            new_name='requirements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vote_code',
        ),
    ]
