# Generated by Django 5.0.1 on 2024-03-25 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votecart_votable_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('student', 'representative')},
        ),
        migrations.RemoveField(
            model_name='votecart',
            name='votable_number',
        ),
        migrations.AddField(
            model_name='votecart',
            name='requirements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_cart',
        ),
    ]
