# Generated by Django 5.0.1 on 2024-03-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecart',
            name='vote_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
